sudo: false
language: node_js
node_js:
  - 4
  - 6
  - node
env:
  - ARANGODB_VERSION=2.8 ARANGO_VERSION=20800
  - ARANGODB_VERSION=3.0 ARANGO_VERSION=30000
  - ARANGODB_VERSION=3.1 ARANGO_VERSION=30100
  - ARANGODB_VERSION=devel ARANGO_VERSION=30200
before_install:
  - curl https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh | bash
script:
  - yarn run lint && yarn run dist && yarn run ci
cache:
  yarn: true
  directories:
    - node_modules
