sudo: false
language: node_js
node_js:
  - 0.12
  - 4.2
  - stable
env:
  - ARANGODB_VERSION=2.6
  - ARANGODB_VERSION=2.7
  - ARANGODB_VERSION=2.8
before_install:
  - curl https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh | bash
script:
  - npm run lint && npm run dist && npm run coveralls
